### ISSUE TITLE
Support top-level sum types

### ISSUE THREAD

**Issue by Tomboyo** [Tomboyo/lily#105]
When a schema is a oneOf composition and has no properties keyword or other composition keywords, it should be treated as a sum type and rendered as a sealed interface of its components.

```
Foo:
  oneOf:
    - properties:
        foo:
          type: string
    - properties:
        bar:
          type: string
```

```
public sealed interface Foo permits FooAnonymous1, FooAnonymous2 {
  public static Anonymous1Builder newFooAnonymous1Builder() { ... }
  public static Anonymous2Builder newFooAnonymous2Builder() {. .. }
}

public record FooAnonymous1(String foo) implements Foo {}
public record FooAnonymous2(String bar) implements Foo {}
```

The interface exposes static factories to create builders for each component.
