### ISSUE TITLE
Prevent OneOf anonymous type name collisions

### ISSUE THREAD

**Issue by Tomboyo** [Tomboyo/lily#89]
Given the following component schema, Lily will try to render multiple classes with the same name. Lily should, if possible, prevent such a name collision from happening.
```yaml
FooStringEmailAlias:
  type: string
Foo:
  oneOf:
    - type: string
      format: email

Bar1:
  type: object
 Bar:
  oneOf:
    - type: object
```
In the `Foo`  case, our naming strategy for anonymous alias types collides with a root-level component. In the `Bar` case, our naming strategy for anonymous objects collides with the root level component.
