### ISSUE TITLE
Handle duplicate OneOf elements

### ISSUE THREAD

**Issue by Tomboyo** [Tomboyo/lily#90]
If an OAS document erroneously lists the same element twice in a OneOf definition, we should ignore duplicate entries and render the OneOf successfully.

```yaml
MyType:
  oneOf:
    - $ref: Foo
    - $ref: Foo #ignore me
    - type: string
    - type: string #ignore me too
```
